name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3.1.0
      with:
        python-version: 3.9
        cache: pip

    - name: Install dependencies
      run: make deps

    - name: Build
      run: make build
